@baseUrl =http://localhost:3000
@endpoint=anomalie
@api={{baseUrl}}/{{endpoint}}

### GET ALL
GET {{api}}

### FIND ONE
@idFindOne=110f9553-3a34-4c22-a8b4-3dcedc5b687d
GET {{api}}/{{idFindOne}}

### CREATE
POST {{api}}
Content-Type: application/json

{
    "date_anomalie":"2025-11-04",
    "enginId":"5b988e20-24a1-41c0-a85c-eb4174eff13f",
    "description":"anomalie 2",
    "source":"INSPECTION", 
    "equipe_execution":"921",
    "obs":"observation",
    "urgence":"MOYENNE",
    "typepanneId":"76051272-5b09-409d-9410-ea7f2777832c",
    "siteId":"65c5b211-4548-4511-9d0a-d53fba6f72fe",
    "status":"NON_PROGRAMMEE",
    "date_execution":"2025-11-05"
}
// "source":"INSPECTION", // "VS" | "VJ" | "INSPECTION"
// "urgence":"MOYENNE", // "TRES_ELEVEE" | "ELEVEE" | "MOYENNE" | "FAIBLE";
// "status":"NON_PROGRAMMEE", // "NON_PROGRAMMEE" | "PROGRAMMEE" | "PDR_PRET" | "ATTENTE_PDR" | "EXECUTE";

### UPDATE
@idUpdate=110f9553-3a34-4c22-a8b4-3dcedc5b687d
PATCH {{api}}/{{idUpdate}}
Content-Type: application/json

{
    "site_id":"86078b82-19ec-4b85-b5ea-6f0c7dc64758",
    "date_anomalie":"2025-11-03",
    "description":"anomalie 1",
    "typepanne_id":"490f0b6a-42d1-4462-bdd9-3a020a4384c7",
    "source":"INSPECTION",
    "urgence":"TRES_ELEVEE",
    "equipe_execution":"921",
    "obs":"observation"
}



### formatted
GET {{api}}/formatted

### backlog dashboard
GET {{api}}/backlog_dashboard


### DELETE
@idDelete=4c2ef5e0-862a-434d-9a01-bac0997a08c7
DELETE {{api}}/{{idDelete}}