@baseUrl =http://localhost:3000
@id = d0bdd140-4e9f-4dc6-b78d-9f818f55aeb7

### GET ALL user
GET {{baseUrl}}/user

### GET USER BY ID
GET {{baseUrl}}/user/{{id}}

### CREATE A USER
POST {{baseUrl}}/user
Content-Type: application/json

{
    "email": "ghalas@gmail.com",
    "password": "12345678",
    "firstName":"ghalas",
    "lastName":"med"
}

### UPDATE A USER BY ID
PATCH {{baseUrl}}/user/{{id}}
Content-Type: application/json

{
    "username":"ilayss",
    "email": "ilayss@email.com"
}

### DELETE A USER BY ID
DELETE {{baseUrl}}/user/{{id}}
