@baseUrl =http://localhost:3000
@endpoint=engin
@api={{baseUrl}}/{{endpoint}}


### GET ALL
GET {{api}}

### FIND ONE
@idFindOne=4a656b41-d98f-4c23-8eb9-b1da69fdae3e
GET {{api}}/{{idFindOne}}

### CREATE
POST {{api}}
Content-Type: application/json

{
    "name":"test",
    "parcId":"2b3dc0d8-8104-469a-9286-9965af76bc0a",
    "siteId":"064ccbbd-023d-4394-af62-9f20bc1ca2a2"
}

### UPDATE
@idUpdate=4a656b41-d98f-4c23-8eb9-b1da69fdae3e
PATCH {{api}}/{{idUpdate}}
Content-Type: application/json

{
    "name":"Foration diesel",
}

### DELETE
@idDelete=5481bc3e-a3e4-4a6f-8d17-bfa0f74fe5ff
DELETE {{api}}/{{idDelete}}
